version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm rebuild bcrypt --build-from-source && npm run start:dev"
    ports:
      - 3001:3000
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - youapp-network
    platform: linux/amd64

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - youapp-network

networks:
  youapp-network:

volumes:
  mongodb_data:
